export default {
  lang_key: "en",
  latitude: "Latitude",
  longitude: "Longitude",
  location_permission_need: "App needs location permission 😢",
  distance: "Distance",
  allow_location: "Allow Location",
  language: "Language",
  check_source_github: "View Source Code On Github",
  check_linkedin_profile: "Check My Profile On Linkedin",
  your_latitude: "Your Latitude",
  your_longitude: "Your Longitude",
  there_are_currently: "There are currently {x} humans in Space ",
  information: "Information",
  home: "Home",
  map: "Map",
  your_location: "Your Location",
  options: "Options",
  next_overhead: "Next overhead at 🕖",
};
