export default {
  lang_key: "en",
  latitude: "Latitude",
  longitude: "Longitude",
  location_permission_need: "App needs location permission 😢",
  distance: "Distance",
  allow_location: "Allow Location",
  language: "Language",
  check_source_github: "View Source Code On Github",
  check_linkedin_profile: "Check My Profile On Linkedin",
  your_latitude: "Your Latitude",
  your_longitude: "Your Longitude",
  there_are_currently: "There are currently {x} humans in Space ",
  information: "Information",
  home: "Home",
  map: "Map",
  your_location: "Your Location",
  options: "Options",
  next_overhead: "Next overhead at 🕖",
  calculating: "Calculating",
  rate_app: "Rate App ⭐⭐⭐⭐⭐",
  would_you_like_to_rate: "Would you like to share your review? This will help and motivate us a lot.",
  rate: "Rate",
  never: "Never",
  not_now: "Not Now",
  infoText1: "The International Space Station (ISS) is a modular space station in low Earth orbit",
  infoText2: "It is a multinational collaborative project between five participating space agencies: NASA 🇺🇸, Roscosmos 🇷🇺, JAXA 🇯🇵, ESA 🇪🇺 and CSA 🇨🇦",
  picture_of_day: "Picture of Day From Nasa",
  picture_of_day_error: "There was an error while fetching the picture of day 😞",
  show_picture_in_browser: "Show Picture In Browser",
  share_image_link: "Share Image Link",
};
