export default {
  lang_key: "tr",
  latitude: "Enlem",
  longitude: "Boylam",
  location_permission_need: "Uygulamanın lokasyon iznine ihtiyacı var 😢",
  distance: "Mesafe",
  allow_location: "Konuma İzin Ver",
  language: "Dil",
  check_source_github: "Github Kaynak Kodunu Görüntüle",
  check_linkedin_profile: "Linkedin Profilimi Görüntüle",
  your_latitude: "Enlemin",
  your_longitude: "Boylamın",
  there_are_currently: "Şu an uzayda {x} insan var",
  information: "Bilgiler",
  home: "Anasayfa",
  map: "Harita",
  your_location: "Konumunuz",
  options: "Ayarlar",
  next_overhead: "En yakın tepeden geçiş 🕖",
  calculating: "Hesaplanıyor",
  rate_app: "Uygulamaya Puan Ver ⭐⭐⭐⭐⭐",
  would_you_like_to_rate: "Yorumunuzu paylaşmak ister misiniz? Bu bize çok yardımcı olacak ve motive edecek.",
  rate: "Oyla",
  never: "Asla",
  not_now: "Şimdi Değil",
  infoText1: "Uluslararası Uzay İstasyonu (ISS), alçak Dünya yörüngesindeki modüler bir uzay istasyonudur",
  infoText2: "Katılan beş uzay ajansı arasında çok uluslu bir işbirliği projesidir: NASA 🇺🇸, Roscosmos 🇷🇺, JAXA 🇯🇵, ESA 🇪🇺 ve CSA 🇨🇦",
  picture_of_day: "Nasa Günün Resmi",
  picture_of_day_error: "Nasa günün resmi getirilirken bir hata oluştu 😞",
  show_picture_in_browser: "Resmi Tarayıcıda Göster",
  share_image_link: "Resim Linkini Paylaş",
};
