export default {
  lang_key: "tr",
  latitude: "Enlem",
  longitude: "Boylam",
  location_permission_need: "Uygulamanın lokasyon iznine ihtiyacı var 😢",
  distance: "Mesafe",
  allow_location: "Konuma İzin Ver",
  language: "Dil",
  check_source_github: "Github Kaynak Kodunu Görüntüle",
  check_linkedin_profile: "Linkedin Profilimi Görüntüle",
  your_latitude: "Konumunun Enlemi",
  your_longitude: "Konumunun Boylamı",
  there_are_currently: "Şu an uzayda {x} insan var",
  information: "Bilgiler",
  home: "Anasayfa",
  map: "Harita",
  your_location: "Konumunuz",
  options: "Ayarlar",
  next_overhead: "En yakın tepeden geçiş 🕖",
  calculating: "Hesaplanıyor",
  rate_app: "Uygulamaya Puan Ver ⭐⭐⭐⭐⭐",
  would_you_like_to_rate: "Yorumunuzu paylaşmak ister misiniz? Bu bize çok yardımcı olacak ve motive edecek.",
  rate: "Oyla",
  never: "Asla",
  not_now: "Şimdi Değil",
};
